## Mastering Python

In [1]:
# Exercise 12:
# Create a 3x3 identity matrix as a list of lists.

In [2]:
import numpy as np 
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
x=[[1 if i==j else 0 for j in range(3)] for i in range(3) ]

In [10]:
print(x[0])
print(x[1])
print(x[2])

[1, 0, 0]
[0, 1, 0]
[0, 0, 1]


In [11]:
# Exercise 44:
# Create a list and set the values between the 25th and 75th percentile to 0.

In [19]:
lst = [10, 20, 30, 40, 50]
percentile_25th = sorted(lst)[int(len(lst) * 0.25)]
print(percentile_25th)
percentile_75th = sorted(lst)[int(len(lst) * 0.75)]
lst = [0 if percentile_25th <= x <= percentile_75th else x for x in lst]
print(lst)

20
[10, 0, 0, 0, 50]
