In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [16]:
import numpy as np

###  Core Feature of python numpy is its ability to utilize numpy array with this we can perfom multidimensional takss smoothly

In [47]:
arr=np.array([["a",2],["b",4]])

In [15]:
print(arr.ndim)# Dimensions of your array
print(arr.shape)#Shape that is number of rows and columns 
print(arr.size)# this diplays the total number of elements in your array 
print(arr.dtype)# Showcases the type of data in your array

2
(2, 2)
4
<U11


In [19]:
# print(np.__version__)
# print(np.show_config())

### Basic Numpy array functions are as follows

In [32]:
# Zeroes Array
zeroes=np.zeros((2,2))
print(zeroes)

[[0. 0.]
 [0. 0.]]


In [64]:
#Ones Array
ones=np.ones((2,2))
print(ones)

[[1. 1.]
 [1. 1.]]


In [43]:
# Identity 
index=np.eye(3,3)
print(index)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [127]:
# Any number array
np.full((2,2),4)

array([[4, 4],
       [4, 4]])

In [123]:
#Random Number array and random number generator
print(np.random.rand(3,3))
print(np.random.randint(1,10))

[[0.73414495 0.25771796 0.44902642]
 [0.96029251 0.03592878 0.46966586]
 [0.59347712 0.12779795 0.22977843]]
5


In [195]:
# Arrange Function numpy
x=np.arange(2,10)
x

array([2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# Get first two rows and first two columns
print(arr[:1,:2])

[['a' '2']]


In [63]:
# Adition and other operations

In [77]:
arr2=zeroes+ones
arr3=zeroes*ones
print(arr2)
print(arr3)#Element wise multiplication not matrix wise

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [76]:
#Square root of each element in the array
y=np.sqrt(x)

In [83]:
# Staistical Functions
print(np.mean(x))
print(np.median(x))

5.5
5.5


In [102]:
# Reshape
arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped=arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [103]:
# Transpose
Transpose=arr.T
print(Transpose)

[[1 4]
 [2 5]
 [3 6]]


In [105]:
# Broadcasting in python 
# This allows us to operate on two different sized arrays by expanding the smaller one to match the size of the larger one
arr2D = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
arr1D = np.array([10, 20, 30])  # Shape (3,)
result = arr2D + arr1D
print(result)

[[11 22 33]
 [14 25 36]]


In [121]:
#Filtering data using numpy
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr>20])
arr[arr>30]=10
print(arr)

[30 40 50]
[10 20 30 10 10]


In [126]:
# Tests wheter zeroes are there in array or not
print(np.all(arr))
# Test if any element is non zero
print(np.any(arr))

True
True


In [135]:
arr = np.array([[10, 20]])
np.repeat(arr,3,axis=0)

array([[10, 20],
       [10, 20],
       [10, 20]])

In [145]:
final=np.zeros((5,5))

In [164]:
# final[0]=1
# final[4]=1
# final[::,0]=1
# final[::,4]=1
# final[2,2]=9

final=np.ones((5,5))
zero=np.zeros((3,3))
zero[1,1]=9
final[1:4,1:4]=zero

In [165]:
print(final)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [171]:
arr=arr2 # creates shallow copies 
arr[0]=2
arr2

array([[2., 2.],
       [1., 1.]])

In [172]:
a=np.ones((3,2))
b=np.full((2,3),2)
print(a)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2 2]
 [2 2 2]]


In [174]:
np.matmul(a,b)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [180]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(arr,axis=1)

array([ 6, 15])

In [182]:
vstack=np.vstack([arr,arr])
vstack

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [184]:
hstack=np.hstack([arr,arr])
hstack

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [191]:
vstack[vstack>3]

array([4, 5, 6, 4, 5, 6])

In [197]:
x[[1,2,3]]

array([3, 4, 5])

In [215]:
vstack[[0,2]]

array([[1, 2, 3],
       [1, 2, 3]])

In [217]:
np.isnan(arr)

array([[False, False, False],
       [False, False, False]])

In [225]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [239]:
vstack2=vstack[::,::-1]

In [240]:
print(vstack)
print(vstack2)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]
 [3 2 1]
 [6 5 4]]


In [243]:
np.setdiff1d(vstack,arr)

array([], dtype=int32)

## Numpy Arrays

In [244]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'array1'
array1 = np.array([0, 10, 20, 40, 60, 80])

# Printing the contents of 'array1'
print("Array1: ", array1)

# Creating a Python list 'array2'
array2 = [10, 30, 40, 50, 70]

# Printing the contents of 'array2'
print("Array2: ", array2)

# Finding and printing the unique values in 'array1' that are not present in 'array2'
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


In [250]:
list1=[1,2,3,4,5,6,7]
np.array(list1)

array([1, 2, 3, 4, 5, 6, 7])

In [251]:
tup=(1,2,3,4,5)
np.array(tup)

array([1, 2, 3, 4, 5])

In [261]:
print(np.all([1,2,3]))
print(np.any([0]))

True
False


In [264]:
# Repeats the array that many times 
np.tile(arr,3)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [266]:
# Indicies of max and min value
arr=np.array([1,4,7,2,3])
np.argmax(arr)

2

In [269]:
# Sorting array
np.sort(arr)

array([1, 2, 3, 4, 7])

In [274]:
np.sort(vstack,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [279]:
x=np.ravel(vstack)
x

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [281]:
x = np.arange(16).reshape((4, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [293]:
np.hsplit(x,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### Create Record Array from Flat Lists

In [322]:
a1 = np.array([1, -2, 3, 4])
a2 = np.array(['Red', 'Green', 'White', 'Orange'])
a3 = np.array([12.20, 15, 20, 40])
result = np.core.records.fromarrays([a1, a2, a3], names='a,b,c')

In [323]:
result=np.array(list(zip(a1,a2,a3)),dtype=[('a', 'i4'), ('b', 'U10'), ('c', 'f4')])

In [324]:
print(result)

[( 1, 'Red', 12.2) (-2, 'Green', 15. ) ( 3, 'White', 20. )
 ( 4, 'Orange', 40. )]


In [321]:
np.sign(a1)

array([1, 1, 1, 1])

# Mathematics

In [333]:
print("Roots of the first polynomial:")
print(np.roots([1, -4, 7]))

Roots of the first polynomial:
[2.+1.73205081j 2.-1.73205081j]


In [339]:
print("Mean of elements:")
print(np.mean(a1))
print(np.mean(vstack,axis=1))

Mean of elements:
1.5
[2. 5. 2. 5.]


# Linear Algebra 

In [350]:
a=np.eye(3,3)
b=np.full((3,3),2)
print("A is : \n",a)
print("B is : \n",b)
print("Dot Product : \n",np.dot(a,b))
print("Outer Product : \n",np.outer(a,b))
print("Cross Product : \n",np.cross(a,b))
print("Determinant : \n",np.linalg.det(b))

A is : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
B is : 
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
Dot Product : 
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
Outer Product : 
 [[2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]]
Cross Product : 
 [[ 0. -2.  2.]
 [ 2.  0. -2.]
 [-2.  2.  0.]]
Determinant : 
 0.0


##### Einstein Summation Convention – Use np.einsum(), useful for optimized tensor calculations.
##### Kronecker Product – Use np.kron(A, B), important in signal processing.
##### Matrix/Vector Norms – Use np.linalg.norm(A, ord), useful for measuring size/magnitude.
##### Condition Number – Use np.linalg.cond(A), helps check numerical stability.
##### Frobenius Norm – Use np.linalg.norm(A, 'fro'), a special case of norms.

# Statistics

In [371]:
# functions
a=np.random.randint(1,101,16).reshape(4,4)
print(a)
print("Max among all : \n",np.max(a))
print("Max along axis 1 that is among rows : \n",np.max(a,axis=1))
print("Max along axis 0 that is among columns : \n",np.max(a,axis=0))
print("Min among all : \n",np.min(a))
print("Min along axis 1 that is among rows : \n",np.min(a,axis=1))
print("Max along axis 0 that is among columns : \n",np.max(a,axis=0))

[[ 3 11 48 45]
 [ 9 23 88 33]
 [ 2  7 92 62]
 [82 40 37 21]]
Max among all : 
 92
Max along axis 1 that is among rows : 
 [48 88 92 82]
Max along axis 0 that is among columns : 
 [82 40 92 62]
Min among all : 
 2
Min along axis 1 that is among rows : 
 [ 3  9  2 21]
Max along axis 0 that is among columns : 
 [82 40 92 62]


In [385]:
np.percentile(np.random.randint(1,11,10),50)

5.0

# Random 

### Find the most frequent value in an array

In [397]:
x = np.random.randint(0, 10, 30)
print(np.sort(x))
print("Most Frequent occuring number :",np.bincount(x).argmax())

[0 0 0 0 1 1 2 3 3 3 3 4 5 5 5 5 6 6 6 6 6 6 6 7 7 8 8 8 9 9]
Most Frequent occuring number : 6


### Permutation function 

In [400]:
print("Array result after using permutation():")
print(np.random.permutation(10))

Array result after using permutation():
[7 3 5 0 4 1 9 2 6 8]
